# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Kuroda Lab
email: ziyuanhe.hzy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kuroda Lab @ UC Davis
  We are an immunology lab at the Center for Comparative Medicine and California National Primate Research Center (CNPRC) at University of California, Davis.
  Our studies aim to determine the roles of monocyte/macrophages and neutrophils in innate immune responses and pathogenesis of infectious diseases such as SIV/AIDS, TB, and co-infections using pediatric, adult and aged adult nonhuman primate models.


baseurl: ""
url: "https://kurodalab-ucdavis.github.io/"

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

#add sitemap to website
plugins:
  - jekyll-sitemap

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
